batch: 32
cache: false
data_yaml: data/processed/road_damage_detection/preprocessed/exp_f_full/dataset.yaml
device: cpu
epochs: 4
fraction: 0.15
imgsz: 320
learning_rate: 0.01
name: exp_f_full
optimizer: Auto
patience: 3
seed: 42
workers: 0
