batch: 16
cache: false
data_yaml: data/processed/road_damage_detection/preprocessed/retrain_v1/dataset.yaml
device: cpu
epochs: 10
exist_ok: true
fraction: 0.5
imgsz: 320
learning_rate: 0.01
model_size: nano
model_weights: yolov8n.pt
name: retrain_v1
optimizer: Auto
patience: 10
plots: true
project: experiments/yolo
save: true
save_period: -1
seed: 42
verbose: true
workers: 0
